[package]
name = "libclamav-formpost-service"
version = "1.0.3-v20231111"
edition = "2021"

[dependencies]
axum = {version = "0.7.4", features = ["multipart"]}
axum-prometheus = "0.6.1"
bitflags = "2.4.2"
chrono = "0.4"
config = {version = "0.13", features = ["toml", "yaml"]}
crc32fast = "1.3.2"
digest = "0.10"
hex = "0.4"
hyper = {version = "1.1", features = ["full"] }
infer = "0.15"
libc = "0.2"
md-5 = "0.10"
serde = {version = "1.0.196", features = ["derive"]}
sha2 = "0.10"
tempfile = "3"
tokio = {version = "1.35.1", features = ["full"]}
tower-http = {version = "0.5", features = ["trace"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}

[build-dependencies]
pkg-config = "0.3"